# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'resumin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for resumin

  pod 'Alamofire', '~> 5.4'
  pod 'Nuke'
  pod 'R.swift', '~> 5.1.0'

end
